[linters]
enable-all = true
disable = [
	"interfacer",
	"gosec",
	"golint",
	"godot",
	"scopelint",
	"maligned",
	"nakedret",
	"paralleltest",
	"varnamelen",
	"exhaustive",
	"exhaustivestruct",
	"wrapcheck",
	"gofumpt",
	"forcetypeassert",

	"sqlclosecheck",
	"rowserrcheck",
]

[linters-settings.nlreturn]
block-size = 2